AllCops:
  Exclude:
    - 'spec/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/*'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Max: 6
