AllCops:
  Exclude:
    - 'spec/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/*'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
